apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: classic-trigger-role
  namespace: classic-tekton-ns
rules:
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["eventlisteners", "triggerbindings", "triggertemplates"]
    verbs: ["get"]
  # Permissions for every EventListener deployment to function
  - apiGroups: [""]
    # secrets are only needed for Github/Gitlab interceptors, serviceaccounts only for per trigger authorization
    resources: ["configmaps", "secrets", "serviceaccounts"]
    verbs: ["get", "list", "watch"]
  # Permissions to create resources in associated TriggerTemplates
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "pipelineresources", "taskruns"]
    verbs: ["create"]
---    
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: classic-trigger-rolebinding
  namespace: classic-tekton-ns
subjects:
- kind: ServiceAccount
  name: classic-trigger-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: classic-trigger-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: classic-trigger-sa
  namespace: classic-tekton-ns