apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  annotations:
    manifestival: new
  name: classic-pipeline-java-triggertemplate
  namespace: classic-tekton-ns
spec:
  params:
    - name: GIT_URL
      description: The repository url to build and deploy.
    - name: GIT_REVISION
      description: The revision to build and deploy.
    - name: GIT_REPO_NAME
      description: The git repository name.
    - name: NAMESPACE
      description: The namespace is used by OpenShift's internal image registry to store the built image.
    - name: SERVICE_ACCOUNT
      description: The ServiceAccount under which to run the Pipeline.
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: classic-pipeline-java-run-
      spec:
        serviceAccountName: $(params.SERVICE_ACCOUNT)
        pipelineRef:
          name: classic-pipeline-java
          namespace: classic-tekton-ns
        resources:
        - name: source
          resourceSpec:
            type: git
            params:
            - name: revision
              value: $(params.GIT_REVISION)
            - name: url
              value: $(params.GIT_URL)
        - name: image
          resourceSpec:
            type: image
            params:
            - name: url
              value: image-registry.openshift-image-registry.svc:5000/$(params.NAMESPACE)/$(params.GIT_REPO_NAME):$(params.GIT_REVISION)