apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener: classic-pipeline-java-eventlistener
  name: classic-pipeline-java-el-route
  namespace: classic-tekton-ns
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-catapp
    weight: 100